language: csharp

sudo: required
dist: trusty

env:
  - CLI_VERSION=1.0.0-preview1-002702

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

mono:
  - latest

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh| bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - dotnet restore
  - dotnet restore linuxtest
  - dotnet build src/*
  - dotnet build test/*
  - ls ~/.nuget/packages/xunit.runner.console
  - ls test/Google.Api.Gax.Tests
  - ls test/Google.Api.Gax.Tests/bin
  - ls test/Google.Api.Gax.Tests/bin/Debug
  - ls test/Google.Api.Gax.Tests/bin/Debug/net451/
  - mono ~/.nuget/packages/xunit.runner.console/2.1.0/tools/xunit.console.exe test/Google.Api.Gax.Tests/bin/Debug/net451/Google.Api.Gax.Tests.dll -parallel none
  - for project in `find test -name '*.Tests'`; do mono ~/.nuget/packages/xunit.runner.console/2.1.0/tools/xunit.console.exe test/$project/bin/Debug/net451/$project.dll -parallel none; done
