language: csharp
mono: none
dotnet: 3.1
dist: xenial

# Install the .NET Core 2.1 runtime as that's what we test against
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-runtime-2.1

script:
  - ./build.sh
