language: csharp

sudo: required
dist: trusty

env:
  - CLI_VERSION=latest

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

mono:
  - latest

install:
  # Download script to install dotnet cli
  - curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh -o ./scripts/obtain/install.sh
  - chmod +x scripts/obtain/install.sh
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  # use bash to workaround bug https://github.com/dotnet/cli/issues/1725
  - sudo bash ./scripts/obtain/install.sh --channel "preview" --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR" --no-path
  # add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - dotnet restore
  - dotnet build src/*
  - dotnet build test/*
  - for project in `find . -name '*.Tests'`; do dotnet test $project test -parallel none; done
