// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test_service.proto
// </auto-generated>
// Original file comments:
//
// Copyright 2016 Google Inc. All Rights Reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Google.Api.Gax.Grpc.Rest.Tests {
  public static partial class Sample
  {
    static readonly string __ServiceName = "google.api.gax.grpc.rest.tests.Sample";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest> __Marshaller_google_api_gax_grpc_rest_tests_SimpleRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> __Marshaller_google_api_gax_grpc_rest_tests_SimpleResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> __Method_SimpleMethod = new grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SimpleMethod",
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleRequest,
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> __Method_MethodWithNoHttpOptions = new grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MethodWithNoHttpOptions",
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleRequest,
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> __Method_BidirectionalStreamingMethod = new grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "BidirectionalStreamingMethod",
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleRequest,
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> __Method_ClientStreamingMethod = new grpc::Method<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "ClientStreamingMethod",
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleRequest,
        __Marshaller_google_api_gax_grpc_rest_tests_SimpleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Google.Api.Gax.Grpc.Rest.Tests.TestServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Sample</summary>
    [grpc::BindServiceMethod(typeof(Sample), "BindService")]
    public abstract partial class SampleBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> SimpleMethod(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> MethodWithNoHttpOptions(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task BidirectionalStreamingMethod(grpc::IAsyncStreamReader<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest> requestStream, grpc::IServerStreamWriter<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> ClientStreamingMethod(grpc::IAsyncStreamReader<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Sample</summary>
    public partial class SampleClient : grpc::ClientBase<SampleClient>
    {
      /// <summary>Creates a new client for Sample</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SampleClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Sample that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SampleClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SampleClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SampleClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse SimpleMethod(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SimpleMethod(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse SimpleMethod(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SimpleMethod, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> SimpleMethodAsync(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SimpleMethodAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> SimpleMethodAsync(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SimpleMethod, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse MethodWithNoHttpOptions(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MethodWithNoHttpOptions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse MethodWithNoHttpOptions(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MethodWithNoHttpOptions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> MethodWithNoHttpOptionsAsync(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MethodWithNoHttpOptionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> MethodWithNoHttpOptionsAsync(global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MethodWithNoHttpOptions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> BidirectionalStreamingMethod(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BidirectionalStreamingMethod(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> BidirectionalStreamingMethod(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_BidirectionalStreamingMethod, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> ClientStreamingMethod(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClientStreamingMethod(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse> ClientStreamingMethod(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_ClientStreamingMethod, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SampleClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SampleClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SampleBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SimpleMethod, serviceImpl.SimpleMethod)
          .AddMethod(__Method_MethodWithNoHttpOptions, serviceImpl.MethodWithNoHttpOptions)
          .AddMethod(__Method_BidirectionalStreamingMethod, serviceImpl.BidirectionalStreamingMethod)
          .AddMethod(__Method_ClientStreamingMethod, serviceImpl.ClientStreamingMethod).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SampleBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SimpleMethod, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(serviceImpl.SimpleMethod));
      serviceBinder.AddMethod(__Method_MethodWithNoHttpOptions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(serviceImpl.MethodWithNoHttpOptions));
      serviceBinder.AddMethod(__Method_BidirectionalStreamingMethod, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(serviceImpl.BidirectionalStreamingMethod));
      serviceBinder.AddMethod(__Method_ClientStreamingMethod, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Google.Api.Gax.Grpc.Rest.Tests.SimpleRequest, global::Google.Api.Gax.Grpc.Rest.Tests.SimpleResponse>(serviceImpl.ClientStreamingMethod));
    }

  }
}
#endregion
