/*
 * Copyright 2016 Google Inc. All Rights Reserved.
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file or at
 * https://developers.google.com/open-source/licenses/bsd
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/endpoint.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Api {

  /// <summary>Holder for reflection information generated from google/api/endpoint.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class EndpointReflection {

    #region Descriptor
    /// <summary>File descriptor for google/api/endpoint.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EndpointReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlnb29nbGUvYXBpL2VuZHBvaW50LnByb3RvEgpnb29nbGUuYXBpGhxnb29n",
            "bGUvYXBpL2Fubm90YXRpb25zLnByb3RvIl0KCEVuZHBvaW50EgwKBG5hbWUY",
            "ASABKAkSDwoHYWxpYXNlcxgCIAMoCRIMCgRhcGlzGAMgAygJEhAKCGZlYXR1",
            "cmVzGAQgAygJEhIKCmFsbG93X2NvcnMYBSABKAhCKAoOY29tLmdvb2dsZS5h",
            "cGlCDUVuZHBvaW50UHJvdG9QAaICBEdBUEliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Api.Endpoint), global::Google.Api.Endpoint.Parser, new[]{ "Name", "Aliases", "Apis", "Features", "AllowCors" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  `Endpoint` describes a network endpoint that serves a set of APIs.
  ///  A service may expose any number of endpoints, and all endpoints share the
  ///  same service configuration, such as quota configuration and monitoring
  ///  configuration.
  ///
  ///  Example service configuration:
  ///
  ///      name: library-example.googleapis.com
  ///      endpoints:
  ///        # Below entry makes 'google.example.library.v1.Library'
  ///        # API be served from endpoint address library-example.googleapis.com.
  ///        # It also allows HTTP OPTIONS calls to be passed to the backend, for
  ///        # it to decide whether the subsequent cross-origin request is
  ///        # allowed to proceed.
  ///      - name: library-example.googleapis.com
  ///        apis: google.example.library.v1.Library
  ///        allow_cors: true
  ///        # Below entry makes 'google.example.library.v1.Library'
  ///        # API be served from endpoint address
  ///        # google.example.library-example.v1.LibraryManager.
  ///      - name: library-manager.googleapis.com
  ///        apis: google.example.library.v1.LibraryManager
  ///        # BNS address for a borg job. Can specify a task by appending
  ///        # "/taskId" (e.g. "/0") to the job spec.
  ///
  ///  Example OpenAPI extension for endpoint with allow_cors set to true:
  ///
  ///      {
  ///        "swagger": "2.0",
  ///        "info": {
  ///          "description": "A simple..."
  ///        },
  ///        "host": "MY_PROJECT_ID.appspot.com",
  ///        "x-google-endpoints": [{
  ///          "name": "MY_PROJECT_ID.appspot.com",
  ///          "allow_cors": "true"
  ///        }]
  ///      }
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Endpoint : pb::IMessage<Endpoint> {
    private static readonly pb::MessageParser<Endpoint> _parser = new pb::MessageParser<Endpoint>(() => new Endpoint());
    public static pb::MessageParser<Endpoint> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Api.EndpointReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Endpoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Endpoint(Endpoint other) : this() {
      name_ = other.name_;
      aliases_ = other.aliases_.Clone();
      apis_ = other.apis_.Clone();
      features_ = other.features_.Clone();
      allowCors_ = other.allowCors_;
    }

    public Endpoint Clone() {
      return new Endpoint(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    ///  The canonical name of this endpoint.
    /// </summary>
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "aliases" field.</summary>
    public const int AliasesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_aliases_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> aliases_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///  DEPRECATED: This field is no longer supported. Instead of using aliases,
    ///  please specify multiple [google.api.Endpoint][google.api.Endpoint] for each of the intented
    ///  alias.
    ///
    ///  Additional names that this endpoint will be hosted on.
    /// </summary>
    public pbc::RepeatedField<string> Aliases {
      get { return aliases_; }
    }

    /// <summary>Field number for the "apis" field.</summary>
    public const int ApisFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_apis_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> apis_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///  The list of APIs served by this endpoint.
    /// </summary>
    public pbc::RepeatedField<string> Apis {
      get { return apis_; }
    }

    /// <summary>Field number for the "features" field.</summary>
    public const int FeaturesFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_features_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> features_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///  The list of features enabled on this endpoint.
    /// </summary>
    public pbc::RepeatedField<string> Features {
      get { return features_; }
    }

    /// <summary>Field number for the "allow_cors" field.</summary>
    public const int AllowCorsFieldNumber = 5;
    private bool allowCors_;
    /// <summary>
    ///  Allowing
    ///  [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), aka
    ///  cross-domain traffic, would allow the backends served from this endpoint to
    ///  receive and respond to HTTP OPTIONS requests. The response will be used by
    ///  the browser to determine whether the subsequent cross-origin request is
    ///  allowed to proceed.
    /// </summary>
    public bool AllowCors {
      get { return allowCors_; }
      set {
        allowCors_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Endpoint);
    }

    public bool Equals(Endpoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!aliases_.Equals(other.aliases_)) return false;
      if(!apis_.Equals(other.apis_)) return false;
      if(!features_.Equals(other.features_)) return false;
      if (AllowCors != other.AllowCors) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= aliases_.GetHashCode();
      hash ^= apis_.GetHashCode();
      hash ^= features_.GetHashCode();
      if (AllowCors != false) hash ^= AllowCors.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      aliases_.WriteTo(output, _repeated_aliases_codec);
      apis_.WriteTo(output, _repeated_apis_codec);
      features_.WriteTo(output, _repeated_features_codec);
      if (AllowCors != false) {
        output.WriteRawTag(40);
        output.WriteBool(AllowCors);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += aliases_.CalculateSize(_repeated_aliases_codec);
      size += apis_.CalculateSize(_repeated_apis_codec);
      size += features_.CalculateSize(_repeated_features_codec);
      if (AllowCors != false) {
        size += 1 + 1;
      }
      return size;
    }

    public void MergeFrom(Endpoint other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      aliases_.Add(other.aliases_);
      apis_.Add(other.apis_);
      features_.Add(other.features_);
      if (other.AllowCors != false) {
        AllowCors = other.AllowCors;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            aliases_.AddEntriesFrom(input, _repeated_aliases_codec);
            break;
          }
          case 26: {
            apis_.AddEntriesFrom(input, _repeated_apis_codec);
            break;
          }
          case 34: {
            features_.AddEntriesFrom(input, _repeated_features_codec);
            break;
          }
          case 40: {
            AllowCors = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
