name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    # We need just the .NET Core 2.1 runtime for testing    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    # We build with .NET Core 3.1 SDK
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: |
        ./build.sh
